version: '3.7'

services:
  api:
    container_name: bobizinho
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:80
    networks:
      - docker-network
    depends_on:
      - postgres
  postgres:
    container_name: bobi_db
    image: postgres:13-alpine
    env_file:
      - .env
    networks:
      - docker-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    volumes:
      - .pasta_db:/var/lib/postgresql/data
networks:
  docker-network:
volumes:
  pasta_db: